#!/bin/sh
#
# Usage: $0 [<host>] [<port>] [<nick>] [<username>] [<realname>]

trap 'rm -rf "$tmpfile"' EXIT HUP INT
tmpfile="/tmp/$0.$$"; touch $tmpfile
In () {
	printf 'WAIT 1\n\rNICK %s\r\n' "${nick:=${3:-$(id -un)}}"
	printf 'USER %s localhost * : %s\r\n' "${3:-$nick}" "${5:-$nick}"
	tail -f "$tmpfile" & while IFS= read -r cmd ; do
		case "$cmd" in
			/join*)
				chan="${cmd#* }"
				printf '%s\r\n' "${cmd#/}"
			;;
			/*)
				printf '%s\r\n' "${cmd#/}"
			;;
			*)
				printf 'PRIVMSG %s :%s\r\n' "$chan" "$cmd"
			;;
		esac
	done
}
	
Out () {
	while IFS= read -r resp ; do
		case "$resp" in
			"PING "*)
				echo "PONG ${resp#* }" >> "$tmpfile"
			;;
			*)
				printf "$resp\n"
			;;
		esac
	done
}

In "$@" | nc "${1:-irc.freenode.net}" "${2:-6667}" | Out
