#!/bin/sh
# See LICENSE file for license details.
#
# Usage: $0 hostname port nick

tmpfile="/tmp/$0.$$"
initcmd="wait 1\nnick $3\nuser $3 8 * : $3"
trap 'rm -rf "$tmpfile"' EXIT HUP INT

(echo -e "$initcmd" > "$tmpfile" &
tail -f "$tmpfile" & 
while read -r command ; do
    case "$command" in
        /join*)
            currentchan="${command#* }"
            echo "${command#/}" 2>/dev/null
        ;;
        /*)
            echo "${command#/}" 2>/dev/null
        ;;
        *)
            echo "PRIVMSG $currentchan :$command"
        ;;
    esac
done) | nc "$1" "$2" | while read -r response ; do
    case "$response" in
        "PING "*)
            echo "PONG ${response#* }" >> "$tmpfile"
        ;;
        *)
            echo "$response"
        ;;
    esac
done
